# -*- coding: utf-8 -*-
"""
phase2_B5E_mis0_corner_orchestrator.py

B5E — mis0 corner robustness refinement

Purpose
-------
This orchestrator performs an exact-single sequential campaign for the mis0-left
corner only. It does NOT use the simultaneous multi-adapter line.

For each case:
1. Writes a temporary single-vehicle multiset.py
2. Runs multi_main.py
3. Copies/annotates the generated CSV
4. Computes a strict/pass diagnostic summary
5. Restores the original multiset.py at the end

Run:
    python phase2_B5E_mis0_corner_orchestrator.py --spec phase2_B5E_mis0_corner_spec.json

Optional quick test:
    python phase2_B5E_mis0_corner_orchestrator.py --spec phase2_B5E_mis0_corner_spec.json --limit 3
"""

from __future__ import annotations

import argparse
import json
import math
import os
import shutil
import subprocess
import sys
import time
from pathlib import Path
from typing import Any, Dict, List

import numpy as np
import pandas as pd


def _as_bool(x: Any) -> bool:
    if isinstance(x, bool):
        return x
    if x is None:
        return False
    if isinstance(x, (int, float, np.integer, np.floating)):
        if not np.isfinite(float(x)):
            return False
        return float(x) > 0.5
    s = str(x).strip().lower()
    return s in {"1", "true", "t", "yes", "y", "pass", "passed"}


def _safe_float(x: Any, default: float = math.nan) -> float:
    try:
        y = float(x)
        return y if math.isfinite(y) else default
    except Exception:
        return default


def _first_existing(df: pd.DataFrame, names: List[str]) -> str | None:
    for n in names:
        if n in df.columns:
            return n
    return None


def _last_value(df: pd.DataFrame, names: List[str], default: Any = None) -> Any:
    c = _first_existing(df, names)
    if c is None or len(df) == 0:
        return default
    return df[c].iloc[-1]


def _max_abs_value(df: pd.DataFrame, names: List[str]) -> float:
    c = _first_existing(df, names)
    if c is None:
        return math.nan
    s = pd.to_numeric(df[c], errors="coerce")
    if not np.isfinite(s).any():
        return math.nan
    return float(np.nanmax(np.abs(s.to_numpy())))


def _min_abs_value(df: pd.DataFrame, names: List[str]) -> float:
    c = _first_existing(df, names)
    if c is None:
        return math.nan
    s = pd.to_numeric(df[c], errors="coerce")
    if not np.isfinite(s).any():
        return math.nan
    return float(np.nanmin(np.abs(s.to_numpy())))


def make_cases(spec: Dict[str, Any]) -> List[Dict[str, Any]]:
    cases = []
    role = spec["mis0_role"]
    grid = spec["corner_grid"]

    for cand in spec["candidate_pathspecs"]:
        for hd in grid["height_delta_m"]:
            for vd in grid["velocity_delta_mps"]:
                case_id = (
                    f"B5E_{cand['candidate_id']}"
                    f"_h{float(hd):+06.0f}"
                    f"_v{float(vd):+05.0f}"
                )
                cases.append({
                    "case_id": case_id.replace("+", "p").replace("-", "m"),
                    "candidate": cand,
                    "height_delta_m": float(hd),
                    "velocity_delta_mps": float(vd),
                    "heading_delta_deg": float(role["role_heading_delta_deg"]),
                    "logical_mis_id": int(role["logical_mis_id"]),
                    "role_name": str(role["role_name"]),
                    "sgn_ini_override": role.get("sgn_ini_override", -1),
                })

    return cases


def render_multiset(spec: Dict[str, Any], case: Dict[str, Any], out_csv_rel: str) -> str:
    base = spec["base_initial_state"]
    target = spec["target"]
    taem = spec["taem_target"]
    cand = case["candidate"]

    h0 = float(base["height_m"]) + float(case["height_delta_m"])
    v0 = float(base["velocity_mps"]) + float(case["velocity_delta_mps"])
    hdg = float(base["heading_angle_deg"]) + float(case["heading_delta_deg"])

    return f'''# -*- coding: utf-8 -*-
"""
AUTO-GENERATED by phase2_B5E_mis0_corner_orchestrator.py

Do not edit this file manually during a B5E run.
The original multiset.py is backed up and restored by the orchestrator.

Case:
  {case["case_id"]}
"""

import math
import numpy as np
from numpy import seterr

seterr(all='raise')

# ------------------------------------------------------------
# Simulation controls
# ------------------------------------------------------------
MAXITER = {int(float(spec.get("generated_maxiter", 60000)))}
t0 = 0
MIN_H = 1e-2
GROUND_H = 5.0
INI_STEP = 0.1

ParamsToGuide = [
    "t", "min_h", "self", "is_main",
    "bank_dwell_sec", "sigma_cmd_ema",
    "cos_delta_psi_eps", "update_L12D_denom_eps",
    "L12D_clip_factor", "L12D_update_alpha",
    "height_tol",
    "quad_epsabs", "quad_epsrel", "quad_limit",
]

GuideMetaDefaults = {{
    "bank_dwell_sec": 8.0,
    "sigma_cmd_ema": 0.15,
    "cos_delta_psi_eps": 1e-3,
    "update_L12D_denom_eps": 1e-6,
    "L12D_clip_factor": 0.98,
    "L12D_update_alpha": 0.15,
    "height_tol": 10.0,
    "quad_epsabs": 1e-7,
    "quad_epsrel": 1e-7,
    "quad_limit": 200,
}}

# ------------------------------------------------------------
# B5E exact-single mis0 corner setup
# ------------------------------------------------------------
TARGET_LON_DEG = {float(target["lon_deg"])}
TARGET_LAT_DEG = {float(target["lat_deg"])}

_TAR_LON = np.deg2rad(TARGET_LON_DEG)
_TAR_LAT = np.deg2rad(TARGET_LAT_DEG)

_PATH_SPECS = [
    dict(
        name="{case["case_id"]}",
        phase2_campaign="B5E_mis0_corner_robustness_refinement",
        phase2_role="{case["role_name"]}",
        role_name="{case["role_name"]}",
        logical_mis_id={int(case["logical_mis_id"])},
        b5e_case_id="{case["case_id"]}",
        b5e_candidate_id="{cand["candidate_id"]}",
        height_delta_m={float(case["height_delta_m"])},
        velocity_delta_mps={float(case["velocity_delta_mps"])},
        role_heading_delta_deg={float(case["heading_delta_deg"])},

        # mis0 refinement knobs
        psi_bias_deg={float(cand["psi_bias_deg"])},
        psi_bias_sgo_on_m={float(cand["psi_bias_sgo_on_m"])},
        psi_bias_sgo_off_m={float(cand["psi_bias_sgo_off_m"])},
        psi_bias_alt_on_m={float(cand["psi_bias_alt_on_m"])},
        psi_bias_alt_off_m={float(cand["psi_bias_alt_off_m"])},
        sgn_ini_override={case["sgn_ini_override"]},
    ),
]

StatusParams = [
    {{
        'MissileInitStatus': {{
            "t": 0,
            "longitude": np.deg2rad({float(base["longitude_deg"])}),
            "latitude": np.deg2rad({float(base["latitude_deg"])}),
            "height": {h0},
            "velocity": {v0},
            "path_angle": np.deg2rad({float(base["path_angle_deg"])}),
            "heading_angle": np.deg2rad({hdg}),
        }},
        'TargetInitStatus': {{
            "longitude": _TAR_LON,
            "latitude": _TAR_LAT,
        }},
        'MissileEndStatus': {{
            "velocity": {float(taem["velocity_mps"])},
            "height": {float(taem["height_m"])},
            "height_tol": 10.0,
            "s": {float(taem["s_go_m"])},
            "heading_angle": None,
            "t": {float(taem["t_end_s"])},
        }},
        'PathSpec': _PATH_SPECS[0],
    }},
]

# ------------------------------------------------------------
# Guidance parameters
# ------------------------------------------------------------
CONSIDER_SIGMA_MAX = True
K_GAMMA_SGP = 3
ERR_TOL = 3e-4
K_SIGMA = 10
K_ALPHA = 5 * np.pi / 1e7 / 1.8

CONTROL_PARAM_LIST = ["m", "attack_angle", "bank_angle"]

GUIDE_SAVE_PARAM = [
    "sigma_max",
    "gamma_sg",
    "s_go",
    "sgo_ref",
    "ref_psi",
    "delta_psi",
    "q",
    "L12D",
    "L12D_E",
    "L12D_alpha",
    "a_tol",
    "aL1",
    "aL2",
    "CL_beg",
    "aL2_orig",
    "ref_sgo",
    "ref_t",
    "ref_L12D",
    "L12D_beg",

    # path shaping diagnostics
    "psi_bias_cmd",
    "psi_bias_w",
    "psi_bias_w_sgo",
    "psi_bias_w_alt",
    "psi_bias_state",
    "cos_delta_psi",
    "L12D_singularity",
    "L12D_den_singularity",
    "L12D_update_hold",
    "sigma_cmd_raw",
    "sigma_cmd_prev",
    "L1_L",
    "BR_times",
    "sgn_ini",
    "end_reason",
    "t_local_end",

    # TAEM/event diagnostics if present in current guidance
    "taem_in_box",
    "taem_reached",
    "taem_reached_event",
    "taem_reached_ever",
    "taem_success_latched",
    "taem_dwell_s",
    "taem_dwell_count",
    "taem_h_err",
    "taem_v_err",
    "taem_s_go_err",
    "close_pass_escape",
]

MAX_EBR2_ITER = 5

STORE_DATA = r"{out_csv_rel}"
'''


def annotate_and_evaluate(csv_path: Path, case: Dict[str, Any], spec: Dict[str, Any]) -> Dict[str, Any]:
    row: Dict[str, Any] = {
        "case_id": case["case_id"],
        "candidate_id": case["candidate"]["candidate_id"],
        "height_delta_m": case["height_delta_m"],
        "velocity_delta_mps": case["velocity_delta_mps"],
        "heading_delta_deg": case["heading_delta_deg"],
        "psi_bias_deg": case["candidate"]["psi_bias_deg"],
        "psi_bias_sgo_on_m": case["candidate"]["psi_bias_sgo_on_m"],
        "psi_bias_sgo_off_m": case["candidate"]["psi_bias_sgo_off_m"],
        "psi_bias_alt_on_m": case["candidate"]["psi_bias_alt_on_m"],
        "psi_bias_alt_off_m": case["candidate"]["psi_bias_alt_off_m"],
        "csv": str(csv_path),
        "run_return_code": 0,
    }

    if not csv_path.exists():
        row.update({
            "decision": "NO_CSV",
            "strict_pass": False,
            "score": 1e9,
        })
        return row

    try:
        df = pd.read_csv(csv_path)
    except Exception as exc:
        row.update({
            "decision": "CSV_READ_ERROR",
            "strict_pass": False,
            "score": 1e9,
            "error": str(exc),
        })
        return row

    if len(df) == 0:
        row.update({
            "decision": "EMPTY_CSV",
            "strict_pass": False,
            "score": 1e9,
        })
        return row

    # Annotate CSV with B5E metadata for later comparison/reporting.
    df["phase2_campaign"] = "B5E_mis0_corner_robustness_refinement"
    df["phase2_role"] = case["role_name"]
    df["logical_mis_id"] = int(case["logical_mis_id"])
    df["b5e_case_id"] = case["case_id"]
    df["b5e_candidate_id"] = case["candidate"]["candidate_id"]
    df["b5e_height_delta_m"] = float(case["height_delta_m"])
    df["b5e_velocity_delta_mps"] = float(case["velocity_delta_mps"])
    df["b5e_heading_delta_deg"] = float(case["heading_delta_deg"])

    try:
        df.to_csv(csv_path, index=False)
    except Exception:
        pass

    last = df.iloc[-1]

    success_cols = spec["acceptance"]["strict_success_columns"]
    success_flags = {}
    for c in success_cols:
        success_flags[c] = _as_bool(last[c]) if c in df.columns else False

    any_success_flag = any(success_flags.values())

    end_reason = str(_last_value(df, ["end_reason"], "") or "")
    strict_end_reason = spec["acceptance"].get("strict_end_reason", "taem_dwell_reached")
    end_reason_ok = (strict_end_reason in end_reason) if end_reason else False

    close_escape = _as_bool(_last_value(df, ["close_pass_escape", "any_close_pass_escape"], False))
    reject_close_escape = bool(spec["acceptance"].get("reject_if_close_pass_escape", True))

    h_err = _safe_float(_last_value(df, ["taem_h_err", "taem_err_h_m", "taem_h_err_final"], math.nan))
    v_err = _safe_float(_last_value(df, ["taem_v_err", "taem_err_v_mps", "taem_v_err_final"], math.nan))
    sgo_err = _safe_float(_last_value(df, ["taem_s_go_err", "taem_err_sgo_m", "taem_s_go_err_final"], math.nan))

    h_tol = float(spec["acceptance"]["reference_tolerances"]["h_tol_m"])
    v_tol = float(spec["acceptance"]["reference_tolerances"]["v_tol_mps"])
    sgo_tol = float(spec["acceptance"]["reference_tolerances"]["s_go_tol_m"])

    # Tolerance fallback only when columns exist.
    have_errs = np.isfinite([h_err, v_err, sgo_err]).any()
    tol_ok = True
    if math.isfinite(h_err):
        tol_ok = tol_ok and (abs(h_err) <= h_tol)
    if math.isfinite(v_err):
        tol_ok = tol_ok and (abs(v_err) <= v_tol)
    if math.isfinite(sgo_err):
        tol_ok = tol_ok and (abs(sgo_err) <= sgo_tol)

    # Strict pass: prefer explicit latch/event columns, require no close-pass escape.
    strict_pass = bool(any_success_flag and (not close_escape if reject_close_escape else True))

    # If no explicit success flags exist, use end_reason + tolerance fallback.
    if not any(c in df.columns for c in success_cols):
        strict_pass = bool((end_reason_ok or tol_ok) and (not close_escape if reject_close_escape else True))

    if strict_pass:
        decision = "PASS_STRICT"
    elif close_escape:
        decision = "FAIL_CLOSE_PASS_ESCAPE"
    elif any_success_flag and close_escape:
        decision = "FAIL_SUCCESS_WITH_ESCAPE"
    elif have_errs and not tol_ok:
        decision = "FAIL_TAEM_ERROR"
    else:
        decision = "FAIL_NO_TAEM_LATCH"

    # Ranking score: lower is better; all passes sort before failures.
    h_norm = abs(h_err) / h_tol if math.isfinite(h_err) else 5.0
    v_norm = abs(v_err) / v_tol if math.isfinite(v_err) else 5.0
    s_norm = abs(sgo_err) / sgo_tol if math.isfinite(sgo_err) else 5.0
    escape_penalty = 100.0 if close_escape else 0.0
    fail_penalty = 1000.0 if not strict_pass else 0.0
    score = fail_penalty + escape_penalty + h_norm + v_norm + s_norm

    row.update({
        "decision": decision,
        "strict_pass": bool(strict_pass),
        "end_reason_last": end_reason,
        "close_pass_escape_last": bool(close_escape),
        "taem_h_err_final": h_err,
        "taem_v_err_final": v_err,
        "taem_s_go_err_final": sgo_err,
        "taem_dwell_s_final": _safe_float(_last_value(df, ["taem_dwell_s", "taem_dwell_s_final"], math.nan)),
        "taem_dwell_count_final": _safe_float(_last_value(df, ["taem_dwell_count", "taem_dwell_count_final"], math.nan)),
        "s_go_final": _safe_float(_last_value(df, ["s_go"], math.nan)),
        "s_go_min_abs": _min_abs_value(df, ["s_go"]),
        "height_final": _safe_float(_last_value(df, ["height"], math.nan)),
        "velocity_final": _safe_float(_last_value(df, ["velocity"], math.nan)),
        "q_max": _max_abs_value(df, ["q"]),
        "bank_angle_max_abs": _max_abs_value(df, ["bank_angle"]),
        "delta_psi_max_abs": _max_abs_value(df, ["delta_psi"]),
        "score": float(score),
    })

    for k, v in success_flags.items():
        row[f"flag_{k}"] = bool(v)

    return row


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--spec", required=True, help="B5E JSON spec file")
    ap.add_argument("--limit", type=int, default=None, help="Run only first N cases for a quick smoke test")
    ap.add_argument("--skip-existing", action="store_true", help="Skip cases whose output CSV already exists")
    ap.add_argument("--timeout-sec", type=float, default=None, help="Per-case subprocess timeout in seconds. Overrides spec timeout_sec.")
    ap.add_argument("--progress-interval-sec", type=float, default=30.0, help="Progress print interval while child process is running.")
    ap.add_argument("--generated-maxiter", type=int, default=None, help="Override MAXITER written into temporary multiset.py.")
    ap.add_argument("--keep-last-multiset", action="store_true", help="Do not restore original multiset.py at the end")
    args = ap.parse_args()

    root = Path.cwd()
    spec_path = Path(args.spec)
    spec = json.loads(spec_path.read_text(encoding="utf-8"))
    if args.generated_maxiter is not None:
        spec["generated_maxiter"] = int(args.generated_maxiter)

    outdir = root / spec["output_dir"]
    runs_dir = outdir / "runs"
    logs_dir = outdir / "logs"
    outdir.mkdir(parents=True, exist_ok=True)
    runs_dir.mkdir(parents=True, exist_ok=True)
    logs_dir.mkdir(parents=True, exist_ok=True)

    multiset_path = root / "multiset.py"
    if not multiset_path.exists():
        raise FileNotFoundError(f"multiset.py not found at: {multiset_path}")

    stamp = time.strftime("%Y%m%d_%H%M%S")
    backup_path = root / f"multiset.py.B5E_backup_{stamp}"
    shutil.copy2(multiset_path, backup_path)

    cases = make_cases(spec)
    if args.limit is not None:
        cases = cases[: int(args.limit)]

    manifest = {
        "experiment": spec["experiment"],
        "created_at": stamp,
        "backup_multiset": str(backup_path),
        "n_cases": len(cases),
        "cases": [c["case_id"] for c in cases],
    }
    (outdir / "phase2_B5E_manifest.json").write_text(json.dumps(manifest, indent=2), encoding="utf-8")

    rows = []

    print(f"[B5E] cases = {len(cases)}")
    print(f"[B5E] output = {outdir}")
    print(f"[B5E] backup = {backup_path}")

    try:
        for idx, case in enumerate(cases, start=1):
            out_csv_rel = str((runs_dir / f"{case['case_id']}.csv").relative_to(root)).replace("\\", "/")
            out_csv_abs = root / out_csv_rel

            print(f"\n[B5E] ({idx}/{len(cases)}) {case['case_id']}")

            if args.skip_existing and out_csv_abs.exists():
                print("[B5E] skip existing CSV")
                rows.append(annotate_and_evaluate(out_csv_abs, case, spec))
                continue

            multiset_text = render_multiset(spec, case, out_csv_rel)
            multiset_path.write_text(multiset_text, encoding="utf-8")

            log_out = logs_dir / f"{case['case_id']}.stdout.txt"
            log_err = logs_dir / f"{case['case_id']}.stderr.txt"

            cmd = [spec.get("python_exe", "python"), spec.get("run_script", "multi_main.py")]
            timeout_sec = float(args.timeout_sec if args.timeout_sec is not None else spec.get("timeout_sec", 900.0))
            progress_interval = max(5.0, float(args.progress_interval_sec))

            t0_run = time.time()
            timed_out = False
            return_code = None

            with open(log_out, "w", encoding="utf-8", errors="ignore") as fout, \
                 open(log_err, "w", encoding="utf-8", errors="ignore") as ferr:
                fout.write(f"[B5E parent] command: {' '.join(cmd)}\n")
                fout.write(f"[B5E parent] generated MAXITER: {spec.get('generated_maxiter', 60000)}\n")
                fout.write(f"[B5E parent] timeout_sec: {timeout_sec}\n")
                fout.flush()

                proc = subprocess.Popen(
                    cmd,
                    cwd=str(root),
                    stdout=fout,
                    stderr=ferr,
                    text=True,
                    shell=False,
                )

                next_progress = time.time() + progress_interval
                while True:
                    return_code = proc.poll()
                    if return_code is not None:
                        break

                    elapsed = time.time() - t0_run
                    if elapsed >= timeout_sec:
                        timed_out = True
                        print(f"[B5E] TIMEOUT: elapsed={elapsed:.1f}s / timeout={timeout_sec:.0f}s")
                        try:
                            proc.kill()
                        except Exception:
                            pass
                        return_code = proc.wait(timeout=10)
                        break

                    if time.time() >= next_progress:
                        print(f"[B5E] child still running: elapsed={elapsed:.0f}s / timeout={timeout_sec:.0f}s")
                        next_progress = time.time() + progress_interval

                    time.sleep(1.0)

            elapsed_s = time.time() - t0_run

            row = annotate_and_evaluate(out_csv_abs, case, spec)
            row["run_return_code"] = int(return_code if return_code is not None else -999)
            row["elapsed_s"] = float(elapsed_s)
            row["timeout_sec"] = float(timeout_sec)
            row["timed_out"] = bool(timed_out)
            row["generated_maxiter"] = int(float(spec.get("generated_maxiter", 60000)))

            if timed_out:
                row["decision"] = "TIMEOUT_" + str(row.get("decision", "NO_DECISION"))
                row["strict_pass"] = False
                row["score"] = 1e9
            elif row["run_return_code"] != 0 and row["decision"] not in {"PASS_STRICT"}:
                row["decision"] = "SUBPROCESS_FAIL_" + str(row["decision"])
                row["strict_pass"] = False
                row["score"] = 1e9

            rows.append(row)

            print(
                f"[B5E] decision={row.get('decision')} "
                f"score={row.get('score')} "
                f"h_err={row.get('taem_h_err_final')} "
                f"v_err={row.get('taem_v_err_final')} "
                f"sgo_err={row.get('taem_s_go_err_final')} "
                f"close_escape={row.get('close_pass_escape_last')} "
                f"elapsed_s={row.get('elapsed_s')} "
                f"timed_out={row.get('timed_out')} "
                f"maxiter={row.get('generated_maxiter')}"
            )

            pd.DataFrame(rows).to_csv(outdir / "phase2_B5E_by_run_partial.csv", index=False)

    finally:
        if args.keep_last_multiset:
            print("[B5E] keeping last generated multiset.py")
        else:
            shutil.copy2(backup_path, multiset_path)
            print("[B5E] original multiset.py restored")

    report = pd.DataFrame(rows)
    if len(report):
        report = report.sort_values(["strict_pass", "score"], ascending=[False, True]).reset_index(drop=True)

    report_path = outdir / "phase2_B5E_by_run.csv"
    report.to_csv(report_path, index=False)

    best = report.head(12).copy() if len(report) else report
    best_path = outdir / "phase2_B5E_best_candidates.csv"
    best.to_csv(best_path, index=False)

    print("\n[B5E] DONE")
    print(f"[B5E] report: {report_path}")
    print(f"[B5E] best  : {best_path}")

    if len(report):
        n_pass = int(report["strict_pass"].astype(bool).sum())
        print(f"[B5E] strict_pass = {n_pass}/{len(report)}")
        print("[B5E] top candidates:")
        cols = [
            "case_id", "candidate_id", "height_delta_m", "velocity_delta_mps",
            "decision", "strict_pass", "score",
            "taem_h_err_final", "taem_v_err_final", "taem_s_go_err_final",
            "close_pass_escape_last"
        ]
        print(report[[c for c in cols if c in report.columns]].head(10).to_string(index=False))


if __name__ == "__main__":
    main()